version: '3.1'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5433:5432

  redis-barber:
    image: 'redis:alpine'
    ports:
      - 6379:6379

  mongo-barber:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
